#!/usr/bin/env bash
# GLOSSARY.md 인덱스 자동 생성
# term-definition 메모리 파일 → .hxsk/GLOSSARY.md (canonical + context + definition 표)
# AVOID: aliases는 포함하지 않음 (lazy lookup 정책, 컨텍스트 비용 절감)
# Usage: bash .hxsk/scripts/glossary-rebuild.sh [project_path]

set -euo pipefail

PROJECT_PATH="${1:-${HXSK_PROJECT_DIR:-.}}"
MEMORIES_DIR="${PROJECT_PATH}/.hxsk/memories/term-definition"
OUTPUT="${PROJECT_PATH}/.hxsk/GLOSSARY.md"

if [[ ! -d "$MEMORIES_DIR" ]]; then
  echo "[glossary-rebuild] term-definition 디렉토리 없음: $MEMORIES_DIR" >&2
  exit 1
fi

# 메모리 파일 목록 (알파벳 순)
FILES=$(find "$MEMORIES_DIR" -name "*.md" -not -name ".gitkeep" | sort)

if [[ -z "$FILES" ]]; then
  echo "[glossary-rebuild] term-definition 메모리 없음" >&2
  exit 0
fi

COUNT=0

# GLOSSARY.md 생성
{
  echo "<!-- AUTO-GENERATED by glossary-rebuild.sh — DO NOT EDIT DIRECTLY -->"
  echo "# GLOSSARY.md"
  echo ""
  echo "> 조작적 정의 인덱스. 상세는 \`.hxsk/memories/term-definition/\` 참조."
  echo "> aliases는 lazy lookup (glossary-detect.sh)으로 처리 — 이 파일에 미포함."
  echo ""
  echo "| canonical | context | definition |"
  echo "|---|---|---|"

  while IFS= read -r file; do
    [[ -z "$file" ]] && continue

    # frontmatter에서 필드 추출 (---...--- 사이)
    CANONICAL=$(grep -m1 "^canonical:" "$file" 2>/dev/null | sed 's/^canonical: *"//' | sed 's/".*$//' | sed "s/^canonical: *'//" | sed "s/'.*$//")
    CONTEXT=$(grep -m1 "^context:" "$file" 2>/dev/null | sed 's/^context: *"//' | sed 's/".*$//' | sed "s/^context: *'//" | sed "s/'.*$//")
    DEFINITION=$(grep -m1 "^definition:" "$file" 2>/dev/null | sed 's/^definition: *"//' | sed 's/".*$//' | sed "s/^definition: *'//" | sed "s/'.*$//")

    # 필수 필드 없으면 스킵
    [[ -z "$CANONICAL" ]] && continue
    [[ -z "$CONTEXT" ]] && CONTEXT="-"
    [[ -z "$DEFINITION" ]] && DEFINITION="-"

    # definition 50자 초과 시 truncate (표 가독성)
    if [[ ${#DEFINITION} -gt 60 ]]; then
      DEFINITION="${DEFINITION:0:57}..."
    fi

    echo "| ${CANONICAL} | ${CONTEXT} | ${DEFINITION} |"
    COUNT=$((COUNT + 1))
  done <<< "$FILES"

  echo ""
  echo "---"
  echo "_Last rebuilt: $(date -u +%Y-%m-%dT%H:%M:%SZ) — ${COUNT} terms_"
} > "$OUTPUT"

echo "GLOSSARY rebuilt: ${COUNT} terms → ${OUTPUT}"
